version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
linters:
  enable:
    - misspell
    - unconvert
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - all
        path: docs/
      - linters:
          - errcheck
        source: defer.*\.(Rollback|Sync|Release)\(
      # 日本語エラーメッセージは大文字始まり警告を無視
      - linters:
          - staticcheck
        text: "ST1005:"
    paths:
      - docs
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/sanosuguru/go-event-ticket-reservation
  exclusions:
    generated: lax
    paths:
      - docs
      - vendor
      - third_party$
      - builtin$
      - examples$
