run:
  timeout: 5m
  modules-download-mode: readonly
  concurrency: 4

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: github.com/sanosuguru/go-event-ticket-reservation

issues:
  exclude-dirs:
    - docs
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: docs/
      linters:
        - all
    # defer での Rollback/Sync/Release は意図的に無視
    - source: "defer.*\\.(Rollback|Sync|Release)\\("
      linters:
        - errcheck
